import { z } from "zod";

export const productSchema = z.object({
  name: z.string().min(1, "Name is required").max(200),
  slug: z.string().min(1).max(200).regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens"),
  type: z.enum(["simple", "variable", "digital", "service", "bundle"]).default("simple"),
  sku: z.string().max(100).optional(),
  short_description: z.string().max(500).optional(),
  long_description: z.string().optional(),
  category_id: z.string().uuid().optional(),
  brand_id: z.string().uuid().optional(),
  regular_price: z.number().positive("Regular price must be positive"),
  sale_price: z.number().positive().optional(),
  cost_price: z.number().positive().optional(),
  vendor_id: z.string().uuid().optional(),
  images: z.array(z.string()).default([]),
  variants: z.array(z.object({
    name: z.string().min(1),
    price: z.number().positive(),
    sku: z.string().optional(),
    stock: z.number().int().nonnegative().default(0),
  })).default([]),
  specifications: z.record(z.string()).default({}),
  tags: z.array(z.string()).default([]),
  featured: z.boolean().default(false),
  status: z.enum(["draft", "published", "archived"]).default("draft"),
  seo: z.object({
    title: z.string().max(70).optional(),
    description: z.string().max(160).optional(),
    og_image: z.string().optional(),
  }).default({}),
});

export const orderSchema = z.object({
  customer_id: z.string().uuid().optional(),
  order_number: z.string().min(1).max(50),
  subtotal: z.number().nonnegative(),
  shipping_cost: z.number().nonnegative().default(0),
  tax: z.number().nonnegative().default(0),
  discount: z.number().nonnegative().default(0),
  total: z.number().nonnegative(),
  status: z.enum(["pending", "processing", "confirmed", "packed", "dispatched", "in-transit", "delivered", "completed", "cancelled", "refunded", "on-hold"]).default("pending"),
  payment_method: z.string().optional(),
  payment_status: z.enum(["pending", "paid", "refunded", "partial-refund"]).default("pending"),
  currency: z.string().length(3).default("USD"),
  storefront_id: z.string().uuid().optional(),
  shipping_address: z.object({
    line1: z.string().min(1),
    line2: z.string().optional(),
    city: z.string().min(1),
    state: z.string().min(1),
    country: z.string().min(1),
    postal_code: z.string().optional(),
  }).optional(),
  tracking_number: z.string().optional(),
  notes: z.string().optional(),
  items: z.array(z.object({
    product_id: z.string().uuid().optional(),
    product_name: z.string().min(1),
    product_image: z.string().optional(),
    variant_info: z.string().optional(),
    quantity: z.number().int().positive(),
    price: z.number().nonnegative(),
    total: z.number().nonnegative(),
  })).min(1, "At least one item is required"),
});

export const storefrontSchema = z.object({
  name: z.string().min(1, "Name is required").max(100),
  slug: z.string().min(1).max(100).regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens"),
  domain_type: z.enum(["subdomain", "custom_domain"]),
  subdomain: z.string().optional(),
  custom_domain: z.string().optional(),
  currency_code: z.string().length(3).default("USD"),
  currency_symbol: z.string().default("$"),
  language_code: z.string().length(2).default("en"),
  country_code: z.string().length(2).optional(),
  tax_rate: z.number().nonnegative().default(0),
  tax_label: z.string().optional(),
  tax_inclusive: z.boolean().default(false),
  is_default: z.boolean().default(false),
  status: z.enum(["active", "inactive"]).default("active"),
  meta_title: z.string().max(70).optional(),
  meta_description: z.string().max(160).optional(),
  catalog_mode: z.boolean().default(false),
  age_verification: z.boolean().default(false),
  min_age: z.number().int().positive().default(18),
});

export const vendorSchema = z.object({
  user_id: z.string().uuid().optional(),
  shop_name: z.string().min(1, "Shop name is required").max(100),
  shop_slug: z.string().min(1).max(100).regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens"),
  shop_description: z.string().max(2000).optional(),
  shop_logo: z.string().optional(),
  shop_banner: z.string().optional(),
  vendor_tier: z.enum(["bronze", "silver", "gold", "platinum", "official_brand", "kauvex_direct"]).default("bronze"),
  commission: z.number().min(0).max(100).default(10),
  status: z.enum(["pending", "approved", "suspended", "rejected"]).default("pending"),
  contact_email: z.string().email().optional(),
  contact_phone: z.string().optional(),
  address: z.string().optional(),
  business_registration: z.string().optional(),
});

export const adCampaignSchema = z.object({
  name: z.string().min(1, "Campaign name is required").max(200),
  vendor_id: z.string().uuid(),
  type: z.enum(["banner", "search", "product_display", "video", "social"]),
  placement: z.string().max(100).optional(),
  budget: z.number().positive("Budget must be positive"),
  daily_budget: z.number().positive().optional(),
  start_date: z.string().datetime(),
  end_date: z.string().datetime().optional(),
  status: z.enum(["draft", "active", "paused", "completed", "cancelled"]).default("draft"),
  target_url: z.string().url().optional(),
  creative_url: z.string().optional(),
  target_audience: z.object({
    locations: z.array(z.string()).optional(),
    categories: z.array(z.string()).optional(),
    min_age: z.number().int().positive().optional(),
    max_age: z.number().int().positive().optional(),
  }).optional(),
  max_cpc: z.number().positive().optional(),
  max_cpm: z.number().positive().optional(),
});

export const warehouseSchema = z.object({
  name: z.string().min(1, "Warehouse name is required").max(200),
  slug: z.string().min(1).max(200).regex(/^[a-z0-9-]+$/, "Slug must be lowercase alphanumeric with hyphens"),
  location: z.string().min(1, "Location is required"),
  address: z.string().min(1, "Address is required"),
  city: z.string().min(1),
  state: z.string().min(1),
  country: z.string().min(1),
  postal_code: z.string().optional(),
  contact_name: z.string().optional(),
  contact_phone: z.string().optional(),
  contact_email: z.string().email().optional(),
  capacity: z.number().int().positive().optional(),
  status: z.enum(["active", "inactive", "maintenance"]).default("active"),
  allows_pickup: z.boolean().default(false),
  allows_delivery: z.boolean().default(true),
  operating_hours: z.object({
    monday: z.string().optional(),
    tuesday: z.string().optional(),
    wednesday: z.string().optional(),
    thursday: z.string().optional(),
    friday: z.string().optional(),
    saturday: z.string().optional(),
    sunday: z.string().optional(),
  }).optional(),
  coordinates: z.object({
    lat: z.number().min(-90).max(90).optional(),
    lng: z.number().min(-180).max(180).optional(),
  }).optional(),
});

export const webhookSchema = z.object({
  name: z.string().min(1, "Webhook name is required").max(100),
  url: z.string().url("A valid URL is required"),
  events: z.array(z.string()).min(1, "At least one event is required"),
  secret: z.string().min(16, "Secret must be at least 16 characters").optional(),
  status: z.enum(["active", "inactive"]).default("active"),
  description: z.string().max(500).optional(),
  retry_count: z.number().int().nonnegative().default(3),
  timeout_ms: z.number().int().positive().default(5000),
});

export const apiKeySchema = z.object({
  name: z.string().min(1, "Key name is required").max(100),
  permissions: z.array(z.object({
    resource: z.string().min(1),
    action: z.string().min(1),
  })).min(1, "At least one permission is required"),
  status: z.enum(["active", "revoked"]).default("active"),
  expires_at: z.string().datetime().optional(),
  ip_whitelist: z.array(z.string()).optional(),
  rate_limit_per_minute: z.number().int().positive().default(60),
});
