#!/usr/bin/env node
/**
 * Workspace Index Generator
 * Scans the Kauvex codebase and writes .opencode/workspace-index.md —
 * a compact orientation map the agent reads before answering.
 * Re-run after any major structural change:
 *   node scripts/workspace-index.mjs
 */
import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(process.cwd());
const OUT = path.join(ROOT, ".opencode", "workspace-index.md");
const SKIP_DIRS = new Set(["node_modules", ".next", ".git", "dist", "build", ".turbo", "generated"]);

async function exists(p) {
  try { await fs.access(p); return true; } catch { return false; }
}

async function list(dir) {
  try { return await fs.readdir(dir, { withFileTypes: true }); } catch { return []; }
}

function titleCase(name) {
  return name
    .replace(/\.(tsx?|jsx?|sql|md)$/, "")
    .split(/[-_.]/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

async function countFiles(dir, ext = null) {
  let total = 0;
  const entries = await list(dir);
  for (const e of entries) {
    if (e.isDirectory()) {
      if (!SKIP_DIRS.has(e.name)) total += await countFiles(path.join(dir, e.name), ext);
    } else if (!ext || e.name.endsWith(ext)) {
      total++;
    }
  }
  return total;
}

async function pageCount(dir) {
  let pages = 0;
  const entries = await list(dir);
  for (const e of entries) {
    if (e.isDirectory()) {
      if (!SKIP_DIRS.has(e.name)) pages += await pageCount(path.join(dir, e.name));
    } else if (e.name === "page.tsx" || e.name === "layout.tsx") {
      pages++;
    }
  }
  return pages;
}

async function summarizeTree(dir, maxDepth = 1) {
  const rows = [];
  const entries = (await list(dir)).filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name)).sort((a, b) => a.name.localeCompare(b.name));
  for (const e of entries) {
    const full = path.join(dir, e.name);
    const files = await countFiles(full);
    if (maxDepth > 1) {
      const sub = await summarizeTree(full, maxDepth - 1);
      rows.push({ name: e.name, files, children: sub });
    } else {
      rows.push({ name: e.name, files });
    }
  }
  return rows;
}

function renderTree(rows, indent = "  ") {
  return rows
    .map((r) => {
      const line = `${indent}- ${r.name} (${r.files} files)`;
      const kids = r.children?.length ? "\n" + renderTree(r.children, indent + "  ") : "";
      return line + kids;
    })
    .join("\n");
}

async function main() {
  const lines = [];
  const stamp = new Date().toISOString().replace("T", " ").slice(0, 19);
  lines.push(`# WORKSPACE INDEX — Kauvex`, ``);
  lines.push(`> Auto-generated by \`node scripts/workspace-index.mjs\`. Regenerate when structure changes. Generated: ${stamp}Z`, ``);

  // Prisma
  const schemaPath = path.join(ROOT, "prisma", "schema.prisma");
  if (await exists(schemaPath)) {
    const schema = await fs.readFile(schemaPath, "utf8");
    const models = schema.match(/^model\s+\w+/gm) ?? [];
    lines.push(`## Database`, ``);
    lines.push(`- Prisma models: ${models.length} (schema.prisma, ${schema.split("\n").length} lines)`);
    const modelNames = models.map((m) => m.split(/\s+/)[1]);
    const kModelCount = modelNames.filter((n) => n.startsWith("K")).length;
    lines.push(`- Sample models: ${modelNames.slice(0, 14).join(", ")}${modelNames.length > 14 ? ", …" : ""} (${kModelCount} models in the K* platform families)`);
  }

  // Migrations
  const migDir = path.join(ROOT, "supabase", "migrations");
  if (await exists(migDir)) {
    const migs = (await list(migDir)).filter((e) => e.name.endsWith(".sql")).map((e) => e.name).sort();
    lines.push(`- Migrations: ${migs.length} (supabase/migrations) — newest: ${migs.slice(-5).map((m) => m.replace(".sql", "")).join(", ")}`);
  }
  lines.push(``);

  // src/lib
  const libDir = path.join(ROOT, "src", "lib");
  if (await exists(libDir)) {
    lines.push(`## src/lib — Engines & Services`, ``);
    const libFiles = (await list(libDir)).filter((e) => !e.isDirectory() && !SKIP_DIRS.has(e.name) && /\.(ts|tsx)$/.test(e.name)).sort((a, b) => a.name.localeCompare(b.name));
    if (libFiles.length) {
      lines.push(`- Top-level modules: ${libFiles.map((f) => titleCase(f.name)).join(", ")}`);
    }
    const libDirs = await summarizeTree(libDir);
    if (libDirs.length) {
      lines.push(`- Module directories:`);
      lines.push(renderTree(libDirs));
    }
    lines.push(``);
  }

  // src/app
  const appDir = path.join(ROOT, "src", "app");
  if (await exists(appDir)) {
    lines.push(`## src/app — Routes & Portals`, ``);
    const top = (await list(appDir)).filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name) && e.name !== "api").sort((a, b) => a.name.localeCompare(b.name));
    lines.push(`- Portals/pages (${top.length} top-level groups):`);
    for (const e of top) {
      const full = path.join(appDir, e.name);
      lines.push(`  - /${e.name} — ${await pageCount(full)} pages`);
    }
    const apiDir = path.join(appDir, "api");
    if (await exists(apiDir)) {
      lines.push(`- /api (${await countFiles(apiDir, ".ts")} route files):`);
      const groups = (await list(apiDir)).filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name)).sort((a, b) => a.name.localeCompare(b.name));
      for (const g of groups) {
        const full = path.join(apiDir, g.name);
        const sub = (await list(full)).filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name)).map((e) => e.name);
        lines.push(`  - /api/${g.name} — ${await countFiles(full, ".ts")} routes${sub.length ? ` (${sub.join(", ")})` : ""}`);
      }
    }
    lines.push(``);
  }

  // Canvas docs
  const canvasDir = path.join(ROOT, "docs", "canvas");
  if (await exists(canvasDir)) {
    lines.push(`## docs/canvas — Master Planning Documents`, ``);
    const docs = (await list(canvasDir)).filter((e) => e.name.endsWith(".md")).sort((a, b) => a.name.localeCompare(b.name));
    for (const d of docs) lines.push(`- ${d.name.replace(/\.md$/, "")}`);
    lines.push(``);
  }

  // Skills & agents
  const skillsDir = path.join(ROOT, ".opencode", "skills");
  if (await exists(skillsDir)) {
    lines.push(`## .opencode — AI Infrastructure`, ``);
    const skills = (await list(skillsDir)).filter((e) => e.isDirectory() && !SKIP_DIRS.has(e.name)).map((e) => e.name).sort();
    lines.push(`- Skills: ${skills.join(", ") || "none"}`);
    const agentDir = path.join(ROOT, ".opencode", "agent");
    if (await exists(agentDir)) {
      const agents = (await list(agentDir)).filter((e) => e.name.endsWith(".md")).map((e) => e.name.replace(/\.md$/, "")).sort();
      lines.push(`- Agents: ${agents.join(", ") || "none"}`);
    }
    lines.push(``);
  }

  // AGENTS.md
  const agentsMd = path.join(ROOT, "AGENTS.md");
  if (await exists(agentsMd)) {
    const content = await fs.readFile(agentsMd, "utf8");
    lines.push(`## Guidance`, ``);
    lines.push(`- AGENTS.md: ${content.split("\n").length} lines — READ FIRST for full project context.`);
  }

  // Global stats
  const srcFiles = await countFiles(path.join(ROOT, "src"));
  lines.push(`- Total src files: ${srcFiles}`, ``);
  lines.push(`---`, ``, `## How to use this index`, ``, `1. Read this file first for fast orientation.`, `2. Drill into specific files when a task needs details.`, `3. Regenerate with \`node scripts/workspace-index.mjs\` after big changes.`);

  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, lines.join("\n"), "utf8");
  console.log(`Index written: ${OUT} (${lines.length} lines)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
